# This is a basic workflow to help you get started with Actions

name: Pyhton Flask App
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
           script:
                   import os
                       from flask import Flask
                       app = Flask(__name__)
                       @app.route("/")
                       def main()
                           return "Welcome!"
                       @app.route('/howareyou')
                       def hello()
                           return 'I am good, how about you?'
                       if __name__ == "__main__"
                       app.run(host="0.0.0.0", port=8080)
       

      - name: Install python
        run: sudo apt-get install -y python python3-pip
        
      - name: Install pyhthon-pip
        run: sudo apt-get install python3-pip
      
      - name: Intall flask
        run: sudo pip install flask

      - name: Run flask app at port 8000
        run: FLASK_APP= ${{ steps.script.outputs.stdout }} flask run --host=0.0.0.0
