# This is a basic workflow to help you get started with Actions

name: Pyhton Flask App
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: build image
        run: docker build . -t my-flask-app:v1

      - name: give authentication
        run: at ~/mypassword | docker login --username ns328 --password .
        
      - name: tag image
        run: docker tag my-flask-app:v1 ghcr.io/ns328/container-images/my-flask-app:v1
        
      - name: push image into ghcr
        run: docker push ghcr.io/ns328/container-images/my-flask-app:v1
